import Head from 'next/head'
import SongPage from '../../components/SongPage';
import { useRouter } from "next/dist/client/router";

export default function Home() {
  const router = useRouter();
  const name = router.query.id;
  return (
    <>
   <Head>
        <title>Wave</title>
        <meta name="description" content="Generated by Kenneth Galang" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SongPage/>
      
    </>
  )
}