import Head from 'next/head'
import Search from "../components/Search";
import styles from '../styles/Home.module.css'

export default function Song() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </>
  )
}
